### ISSUE TITLE
Error when starting up Minecraft: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Pyrotech

### ISSUE THREAD

**Issue by Somebody139** [codetaylor/pyrotech-1.12#319]
heres the full crash:

Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Pyrotech (pyrotech)
Caused by: java.lang.NoClassDefFoundError: com/codetaylor/mc/pyrotech/modules/tech/bloomery/tile/TileBloomery
	at com.codetaylor.mc.pyrotech.modules.tech.bloomery.init.BlockInitializer.onRegister(BlockInitializer.java:25)
	at com.codetaylor.mc.pyrotech.modules.tech.bloomery.ModuleTechBloomery.onRegister(ModuleTechBloomery.java:200)
	at com.codetaylor.mc.athenaeum.module.ModuleBase.onPreInitializationEvent(ModuleBase.java:296)
	at com.codetaylor.mc.pyrotech.modules.tech.bloomery.ModuleTechBloomery.onPreInitializationEvent(ModuleTechBloomery.java:134)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter.lambda$null$2(ModuleEventRouter.java:43)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter$$Lambda$1132/1675847026.accept(Unknown Source)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter.fireEvent(ModuleEventRouter.java:202)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter.lambda$new$4(ModuleEventRouter.java:43)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter$$Lambda$213/1184639304.routeEvent(Unknown Source)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter.routeFMLStateEvent(ModuleEventRouter.java:111)
	at com.codetaylor.mc.athenaeum.module.ModuleManager.routeFMLStateEvent(ModuleManager.java:76)
	at com.codetaylor.mc.pyrotech.ModPyrotech.onPreInitializationEvent(ModPyrotech.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.codetaylor.mc.pyrotech.modules.tech.bloomery.tile.TileBloomery
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 52 more
Caused by: java.lang.NoClassDefFoundError: com/codetaylor/mc/pyrotech/library/spi/tile/TileNetBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 54 more
Caused by: java.lang.ClassNotFoundException: com.codetaylor.mc.pyrotech.library.spi.tile.TileNetBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 58 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 336221504 bytes (320 MB) / 1073741824 bytes (1024 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version           | Source                                      | Signature                                |
	|:----- |:----------------- |:----------------- |:------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2            | minecraft.jar                               | None                                     |
	| LCH   | mcp               | 9.42              | minecraft.jar                               | None                                     |
	| LCH   | FML               | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCH   | forge             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar               | None                                     |
	| LCH   | creativecoredummy | 1.0.0             | minecraft.jar                               | None                                     |
	| LCH   | srm-hooks         | 1.12.2-1.0.0      | minecraft.jar                               | None                                     |
	| LCH   | jei               | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                   | None                                     |
	| LCH   | athenaeum         | 1.12.2-1.19.1     | athenaeum-1.12.2-1.19.1.jar                 | None                                     |
	| LCH   | quark             | r1.6-177          | Quark-r1.6-177.jar                          | None                                     |
	| LCH   | autoreglib        | 1.3-32            | AutoRegLib-1.3-32.jar                       | None                                     |
	| LCH   | bookshelf         | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | chaotica          | 4.8.5             | Chaotica_v4.8.51fixed[1.12.2].jar           | None                                     |
	| LCH   | chiselsandbits    | 14.33             | chiselsandbits-14.33.jar                    | None                                     |
	| LCH   | opframe           | 1.4.0             | OnlinePicFrame_v1.4.40_mc1.12.2.jar         | None                                     |
	| LCH   | creativecore      | 1.9.9             | CreativeCore_v1.9.90_mc1.12.2.jar           | None                                     |
	| LCH   | dropt             | 1.12.2-1.18.0     | dropt-1.12.2-1.18.0.jar                     | None                                     |
	| LCH   | elementalmastery  | 1.3               | elementalmastery-1.3.1.jar                  | None                                     |
	| LCH   | eplus             | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | forgelin          | 1.8.4             | Forgelin-1.8.4.jar                          | None                                     |
	| LCH   | futuremc          | 0.2.4.1           | future-mc-1.12.2-0.2.4.1.jar                | None                                     |
	| LCH   | infernalmobs      | 1.7.6             | InfernalMobs-1.12.2.jar                     | None                                     |
	| LCH   | mantle            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                    | None                                     |
	| LCH   | llibrary          | 1.7.19            | llibrary-1.7.19-1.12.2.jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | mowziesmobs       | 1.5.8             | mowziesmobs-1.5.8.jar                       | None                                     |
	| LCH   | mysticalworld     | 1.12.2-1.7.1      | mysticalworld-1.12.2-1.7.1.jar              | None                                     |
	| LCH   | patchouli         | 1.0-20            | Patchouli-1.0-20.jar                        | None                                     |
	| LCH   | placeableitems    | 3.3               | placeableitems-3.3.jar                      | None                                     |
	| LCE   | pyrotech          | 1.12.2-1.4.22     | pyrotech-1.12.2-1.4.22.jar                  | None                                     |
	| LC    | roughmobs         | 2.0.0             | roughmobs2-1.12.2_2.0.15.jar                | None                                     |
	| LC    | secretroomsmod    | 5.6.4             | secretroomsmod-1.12.2-5.6.4.jar             | None                                     |
	| LC    | sereneseasons     | 1.2.18            | SereneSeasons-1.12.2-1.2.18-universal.jar   | None                                     |
	| LC    | tconstruct        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar            | None                                     |
	| LC    | toughasnails      | 3.1.0.139         | ToughAsNails-1.12.2-3.1.0.139-universal.jar | None                                     |
	| LC    | valiux            | 2.2               | ValiuxReborn-2.2.1.jar                      | None                                     |
	| LC    | worleycaves       | 1.5.1             | worleycaves-1.5.1.jar                       | None                                     |
	| LC    | mysticallib       | 1.12.2-1.9.0      | mysticallib-1.12.2-1.9.0.jar                | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
No More Glowing Pots (nomoreglowingpots-1.0.jar)
  zabi.minecraft.nomoreglowingpots.PotionTransformer
FutureMC (future-mc-1.12.2-0.2.4.1.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.48' Renderer: 'GeForce GTX 1060 3GB/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

**Comment by codetaylor** [comment]
You need to upgrade Pyrotech to `1.4.30+` or downgrade Athenaeum to `1.18.1`.

**Comment by Somebody139** [comment]
Ok
