### ISSUE TITLE
Guide book doesn't work.

### ISSUE THREAD

**Issue by AssasinAsha** [codetaylor/pyrotech-1.12#360]
#### Issue Description

Can't use the mod's guide book.

#### What Happens

The book doesn't spawn on first world load. It exists in the creative inventory, but when I take it from there and right-click it, nothing happens.
There's an error logged in the console when the game loads to main menu.

#### What You Expect to Happen

Book working as intended.

#### Crash Log

Not a crash log (the game loads and works) but here's the error. Yeah, most of it's Patchouli, but the end bit seems relevant.
Honestly, I'm not even sure if it's on your side or Vazkii's:

```
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: java.lang.RuntimeException: Error while loading entry pyrotech:bloom/dense_redstone
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents.lambda$reload$3(BookContents.java:149)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.util.HashMap.forEach(HashMap.java:1289)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.book.BookContents.reload(BookContents.java:145)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:201)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.util.HashMap$Values.forEach(HashMap.java:981)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.book.BookRegistry.reload(BookRegistry.java:87)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.client.base.ClientProxy.loadComplete(ClientProxy.java:35)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at vazkii.patchouli.common.base.Patchouli.loadComplete(Patchouli.java:47)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[20:50:18] [Client thread/INFO] [STDERR]: [vazkii.patchouli.client.book.BookContents:reload:163]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.RuntimeException: Error while loading entry pyrotech:bloom/dense_redstone page 1
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:182)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at vazkii.patchouli.client.book.BookContents.lambda$reload$3(BookContents.java:147)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 55 more
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: Caused by: java.lang.RuntimeException: Missing packed data for: pyrotech:crafting/anvil_granite
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.codetaylor.mc.pyrotech.packer.PackAPI.getImageData(PackAPI.java:29)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at com.codetaylor.mc.pyrotech.modules.plugin.patchouli.components.PackedImageComponent.build(PackedImageComponent.java:34)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at vazkii.patchouli.client.book.template.component.ComponentCustom.build(ComponentCustom.java:25)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at vazkii.patchouli.client.book.template.BookTemplate.lambda$build$0(BookTemplate.java:116)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at java.util.ArrayList.forEach(ArrayList.java:1259)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at vazkii.patchouli.client.book.template.BookTemplate.build(BookTemplate.java:114)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:24)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:180)
[20:50:18] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:644]: 	... 56 more
```

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2855
* CraftTweaker:N/A
* Dropt: 1.12.2-1.18.0
* Pyrotech: 1.12.2-1.5.13
* Athenaeum: 1.12.2-1.19.2

**Comment by codetaylor** [comment]
Patchouli version?

**Comment by AssasinAsha** [comment]
Can't believe I forgot, sorry about it. 1.0-23.6

**Comment by codetaylor** [comment]
I am unable to reproduce this in a fresh instance with only the following mods at the specified versions:

```
Minecraft: 1.12.2
Forge: 14.23.5.2855
Dropt: 1.12.2-1.18.0
Pyrotech: 1.12.2-1.5.13
Athenaeum: 1.12.2-1.19.2
Patchouli: 1.0-20
```

I tested in the dev environment as well as a stand-alone environment with all new builds downloaded from CurseForge. I used both creative and survival worlds. Everything works as expected in all tests.

Please include a link to your entire log file using a service like pastebin or hastebin.

**Comment by codetaylor** [comment]
Performed additional tests using `Patchouli: 1.0-23.6` with identical results. Still unable to reproduce.

**Comment by AssasinAsha** [comment]
Okay I think I get it.
The whole instance was part of the modpack PyroThermaCraft. The book didn't work from the start, then I updated all the mods I could and then, in prep for the report, I stripped all other mods down to the essentials here. Except I forgot about configs.
On a hunch I deleted pyrotech configs and restarted. Got the book working.

So, I'm sorry for bothering you. This seems to be the case of wrong configs by the pack maker. Since the pack hasn't been updated in months, I'm on my own trying to fix it.

That will teach me to make a clean install of all things.

**Comment by codetaylor** [comment]
No worries. I'm glad you got it working and thanks for letting me know.

**Comment by AssasinAsha** [comment]
... I can't believe it.
No wonder it didn't work.
The Patchouli plugin in the modules.cfg file was set to false.
Setting it back on fixed the original issue.
Why in the world would someone install your (base minecraft behavior changing, I mean, you gate _furnace_ behind _nether_) mod and then disable documentation will remain a mystery to me.
Right, that's it on that front. Issue has been resolved entirely.

This is just for dear people from the future.
Again, sorry for the bother and cheers!
