### ISSUE TITLE
problems with the mod

### ISSUE THREAD

**Issue by BENDY659** [codetaylor/pyrotech-1.12#398]
I wanted to add this mod to my assembly (as for me the best mod), but it says to me that I need an older java. And what is needed? i ran on "jre1.8.0_341"
--------------------------------------------------------------------------------------------------------------------------------------------
I used the translator Ru ---> Eng, so there may be errors somewhere, I'm sorry

**Comment by codetaylor** [comment]
That's weird. It should work fine on JRE 1.8. Do you have a log of the error?

**Comment by BENDY659** [comment]
I don't know if this is...
-------------------------------------------------------------------------------------------------------------------------------------------

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ApotheosisCore (apotheosis-1.12.2-1.12.5.jar)
  darkness (darkness-forge-1.12.x-0.4.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
  CTMCorePlugin (ctm-mc1.12.2-1.0.2.31.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  BlurPlugin (blur-1.0.4-14.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  ForgelinPlugin (forgelin-1.8.4.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  B3M_CorePlugin (b3m-1.12.2-17.jar)
  TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  CreativePatchingLoader (creativecore_v1.10.70_mc1.12.2.jar)
  HCASM (hammerlib-1.12.2-2.0.6.32.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 8/4/22 7:32 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at buildcraft.lib.registry.RegistrationHelper.onRegisterBlocks(RegistrationHelper.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_116_RegistrationHelper_onRegisterBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at buildcraft.lib.registry.RegistrationHelper.onRegisterBlocks(RegistrationHelper.java:59)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_116_RegistrationHelper_onRegisterBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by codetaylor** [comment]
Looks like you've run out of block ids.

> java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.

Try https://www.curseforge.com/minecraft/mc-mods/notenoughids

**Comment by BENDY659** [comment]
I'll try and post....

**Comment by BENDY659** [comment]
Thanks Chel! YouIt works!!! You saved my build
